core/accounts/urls.py
from django.urls import path
from .views import (user_login,
                    user_logout,
                    user_register,
                    current_subject_user,
                    next_random_question)


app_name = 'accounts'
urlpatterns = [
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register'),
    path('add/current_subject/',
         current_subject_user,
         name='add_current_subject'),
    path('get/random/question/<int:subject_pk>/',
         next_random_question,
         name='random_question')
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/questions/urls.py
from django.urls import path
from .views import (add_subject_view,
                    subject_list,
                    delete_subject_view,
                    add_question_view,
                    show_all_questions,
                    delete_questions)


app_name = 'questions'
urlpatterns = [
    path('add/', add_subject_view, name='add'),
    path('subject/list/', subject_list, name='list'),
    path('subject/delete/<int:pk>/',
         delete_subject_view,
         name='delete'),
    path('question/add/<int:subject_pk>/',
         add_question_view,
         name='add_question'),
    path('questions/all/<int:subject_pk>/',
         show_all_questions,
         name='all_questions'),
    path('questions/delete_questions/<int:question_pk>/',
         delete_questions,
         name='delete_questions')
]

core/templates/includes/footer.html
<div class="footer">
                &#169;2021 Все права защищены
            </div>

core/templates/includes/header.html
<div class="top_nav">
                <div class="logo">
                    <span class='logo-for'>FOR</span><span class='logo-test'>TEST</span>
                </div>

                <div class="top-menu">

                    <div class="row">

                        <div class="col-xl-8 col-sm-12 col-md-12 col-lg-8 col-12">
                            <div class="dropdown">
                                <div class="select">
                                    {% if user.is_authenticated %}
                                        {% if current_subject_user %}
                                            <span>{{ current_subject_user.title }}</span> 
                                        {% elif subjects %}
                                            <span>Выберите тему</span>
                                        {% else %}
                                            <span>Вы не добавили ни одного предмета</span>
                                        {% endif %}
                                    

                                    {% else %}
                                    <span>Чтобы выбрать тему необходимо авторизоваться</span>
                                    {% endif %}
                                    
                                    <i class="fa fa-chevron-left"></i>
                                </div>
                                {% if user.is_authenticated %}
                                <ul class="dropdown-menu">

                                    {% csrf_token %}
                                    {% if user.is_authenticated %}
                                    
                                    {% for subject in subjects %}
                                        <li class='drop-item' data-pk={{ subject.pk }}>{{ subject.title }}</li>
                                    {% endfor %}
                                    {% else %}
                                        <li>Чтобы выбрать предмет, необходимо авторизоваться</li>
                                    {% endif %}
                                </ul>
                                {% endif %}
                                
                            </div>


                        </div>

                        <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
                            <div class="nav_link">
                                {% if user.is_authenticated %}
                                <ul>
                                    <li>{{ user.username }}</li>
                                    <li><a href="{% url 'accounts:logout' %}">Выйти</a></li>
                                </ul>
                                {% else %}
                                <ul>
                                    <li><a href="#" data-bs-toggle="modal" data-bs-target="#modal_auth">Войти</a></li>
                                    <li><a href="" data-bs-toggle='modal'
                                            data-bs-target="#modal_reg">Зарегестрироваться</a></li>
                                </ul>
                                {% endif %}
                                

                            </div>
                        </div>

                    </div>




                </div>


            </div>

core/templates/includes/modal_add_questions.html
<div class="modal fade" id="modal_add_subject" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="modal_reg_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modal_reg_label">Добавить предмет</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">

                        <form method='POST' class='add_subject_form' action="{% url 'questions:add' %}">
                            <div class="modal_reg_info">
                            </div>


                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="login" class="form-label">Название предмета</label>
                                {{ add_subject.title}}
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Описание предмета</label>
                                {{ add_subject.description}}
                            </div>
                            <button type="submit" class="btn btn-primary">Добавить предмет</button>
                        </form>
                    </div>

                </div>
            </div>
        </div>

core/templates/includes/modal_auth.html
<div class="modal fade" id="modal_auth" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="modal_auth_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modal_auth_label">Авторизация</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">

                        <form method='POST' action="{% url 'accounts:login' %}" class='auth_form'>


                            <div class="modal_auth_info">
                            {% if messages %}


                                {% for message in messages %}
                                        {{ message }} 
                                {% endfor %} 


                            {% endif %}
                            </div>


                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="login" class="form-label">Логин</label>
                                <input type="text" class="form-control" id="auth_login" name='username' required>
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Пароль</label>

                                <input type="password" class="form-control" id="auth_password" name='password' required>
                            </div>
                            <button type="submit" class="btn btn-primary">Войти</button>
                        </form>

                    </div>

                </div>
            </div>
        </div>

<script>


</script>

core/templates/includes/modal_question.html
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable modal-xl">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Ответ на вопрос</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                                {{ user.current_questions.answer_question.first.answer |safe}}
                        <img src="img/预览图_千图网_编号25688649.jpg" alt="">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

core/templates/includes/modal_reg.html
 <div class="modal fade" id="modal_reg" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="modal_reg_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modal_reg_label">Регистрация</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method='POST' class='reg_form' action="{% url 'accounts:register' %}">
                            <div class="modal_reg_info">
                            </div>


                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="login" class="form-label">Логин</label>
                                {{ reg_form.username }}
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Пароль</label>
                                {{ reg_form.password }}
                            </div>
                            <div class="mb-3">
                                <label for="password2" class="form-label">Повторите пароль</label>
                                {{ reg_form.password1 }}
                            </div>
                            <div class="mb-3">
                                <label for="email" class="form-label">Email</label>
                                {{ reg_form.email }}
                            </div>
                            <div class="mb-3">
                                <label for="first_name" class="form-label">Имя</label>
                                {{ reg_form.first_name }}
                            </div>
                            <div class="mb-3">
                                <label for="last_name" class="form-label">Фамилия</label>
                                {{ reg_form.last_name }}
                            </div>
                            <button type="submit" class="btn btn-primary">Зарегестрироваться</button>
                        </form>
                    </div>

                </div>
            </div>
        </div>

core/templates/includes/sidebar.html
<div class="col-4">

                    <div class="menu-btn">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>

                    <div class="menu">
                       <nav>
                            <li><a href="{% url 'index' %}">Главная</a></li>

                       {% if user.is_authenticated %}
                            <li><a href="#" data-bs-toggle="modal" data-bs-target="#modal_add_subject">Добавить предмет</a></li>
                            <li><a href="{% url 'questions:list' %}">Мои предметы</a></li>

                       {% endif %} 
                            <li><a href="#">О нас</a></li>
                            <li><a href="#">Контакты</a></li>
                        </nav>
                    </div>


                </div>