core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/questions/urls.py
from django.urls import path
from .views import (add_subject_view,
                    subject_list,
                    delete_subject_view,
                    add_question_view,
                    show_all_questions,
                    delete_questions)


app_name = 'questions'
urlpatterns = [
    path('add/', add_subject_view, name='add'),
    path('subject/list/', subject_list, name='list'),
    path('subject/delete/<int:pk>/',
         delete_subject_view,
         name='delete'),
    path('question/add/<int:subject_pk>/',
         add_question_view,
         name='add_question'),
    path('questions/all/<int:subject_pk>/',
         show_all_questions,
         name='all_questions'),
    path('questions/delete_questions/<int:question_pk>/',
         delete_questions,
         name='delete_questions')
]

core/questions/models.py
from django.db import models
from django.conf import settings


class SubjectModel(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,
                               verbose_name='Автор')
    description = models.TextField(verbose_name='Описание предмета',
                                   blank=True,
                                   null=True)
    create_date = models.DateTimeField(verbose_name='Дата создания',
                                       auto_now_add=True)
    
    def __str__(self):
        return f'Предмет "{self.title}" автора -> {self.author.username}'
    
    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы' 


class QuestionsModel(models.Model):
    subject = models.ForeignKey(SubjectModel,
                                on_delete=models.CASCADE,
                                verbose_name='Предмет',
                                related_name='questions')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             verbose_name='Пользователь')
    question = models.TextField(blank=True, null=False)

    def __str__(self):
        return f'Вопрос по предмету {self.subject} -> {self.question}'

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class AnswerModel(models.Model):
    subject = models.ForeignKey(SubjectModel,
                                on_delete=models.CASCADE,
                                related_name='answers'
                                )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    question = models.ForeignKey(QuestionsModel,
                                 on_delete=models.CASCADE,
                                 related_name='answer_question')
    answer = models.TextField(blank=True, null=False)

    def __str__(self):
        return f'Ответ на вопрос {self.question}'
    
    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

core/questions/forms.py
from ckeditor import fields
from django import forms
from django.forms.formsets import formset_factory
from django.forms.models import inlineformset_factory
from .models import SubjectModel, QuestionsModel, AnswerModel
from ckeditor_uploader.widgets import CKEditorUploadingWidget


class AddSubjectForm(forms.ModelForm):

    class Meta:
        model = SubjectModel
        fields = ('title', 'description')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control',
                                            'placeholder': 'Название предмета'}),
            'description': forms.Textarea(attrs={'class': 'form-control',
                                                 'placeholder': 'Описание'})
        }


class QuestionForm(forms.Form):
    question = forms.CharField(widget=CKEditorUploadingWidget, label='Вопрос')
    answer = forms.CharField(widget=CKEditorUploadingWidget, label='Ответ')


QuestionFormSet = formset_factory(QuestionForm)

core/questions/views.py
from django.contrib.messages.api import success
from django.forms.models import inlineformset_factory
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.forms import inlineformset_factory
from .forms import AddSubjectForm, QuestionFormSet
from .models import AnswerModel, QuestionsModel, SubjectModel
import json


def subject_list(request):
    if request.user.is_authenticated:
        user = request.user
        subjects = SubjectModel.objects.filter(author=user).order_by('-create_date')
        return render(request,
                      'questions/subject_list.html',
                      {'subjects': subjects})



def add_subject_view(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = AddSubjectForm(request.POST)
            if form.is_valid():
                subject = form.save(commit=False)
                subject.author = request.user
                subject.save()
                messages.success(request, f'Предмет {subject.title} добавлен')
                return redirect('questions:list')
    else:
        messages.error(request, 'Чтобы добавить предмет, необходима авторизация')
        return redirect('/')


def delete_subject_view(request, pk):
    if request.user.is_authenticated:
        subject = SubjectModel.objects.get(pk=pk)
        if subject.author == request.user:
            subject.delete()
            messages.success(request, f'Предмет {subject.title} удален')
            return redirect('questions:list')


def add_question_view(request, subject_pk):
    if request.user.is_authenticated:
        subject = SubjectModel.objects.get(pk=subject_pk)
        if request.method == 'POST':
            data = request.POST
            data = dict(data)
            print(len(data))
            for key in data:
                print(key)
                if key == 'csrfmiddlewaretoken':
                    continue
                question = QuestionsModel.objects.create(subject=subject,
                                                         user=request.user,
                                                         question=data[key][0])
                question.save()

                answer = AnswerModel.objects.create(subject=subject,
                                                    user=request.user,
                                                    question=question,
                                                    answer=data[key][1])
                answer.save()
                print(answer)
            messages.success(request, f'Вопросы по предмету {subject.title} успешно добавлены')
            return JsonResponse({'status': 201})
        else:
            return render(request,
                      'questions/add_question_and_subject.html',
                      {'subject_pk': subject_pk,
                       'subject': subject})


def show_all_questions(request, subject_pk):
    subject = SubjectModel.objects.get(pk=subject_pk)
    return render(request,
                  'questions/questions_list.html',
                  {'subject': subject})


def delete_questions(request, question_pk):
    question = get_object_or_404(QuestionsModel, pk=question_pk)
    question.delete()
    messages.success(request, f'Вопрос успешно удален')
    return redirect(request.META.get('HTTP_REFERER'))

core/templates/questions/add_question_and_subject.html
{% extends '../main/base.html' %}

{% block content %}

<div class="col-lg-8">

    <div class="row">
        <div class="col-lg-12 question_form">
            <h4 class='mb-3'>Добавление вопросов по предмету {{ subject.title }}</h4>
            
            <form action="">
                {% csrf_token %}
                <div id="question_form">
                    <div class="row mb-3">
                    <div class="col-lg-6 mb-3">
                        <label for="question">Вопрос 1</label>
                        <textarea id="question1" name="question1" rows=20></textarea>
                    </div>
                    <div class="col-lg-6 mb-3">
                        <label for="answer">Ответ на вопрос 1</label>
                        <textarea id="answer1" name="answer1" rows=20></textarea>
                    </div>
                    </div>
                    <hr>
                </div>
                
            </form>

            <button id='add_question' class='btn btn-success'>Еще вопрос</button>
            <button id='save_questions' class='btn btn-primary'>Сохранить</button>


                <script>

                   

                    tinymce.init({
                        selector: '#question1',
                        plugins: 'a11ychecker advcode casechange export formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
                        toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter pageembed permanentpen table',
                        toolbar_mode: 'floating',
                        tinycomments_mode: 'embedded',
                        tinycomments_author: 'Author name',
                        });

                    tinymce.init({
                        selector: '#answer1',
                        plugins: 'a11ychecker advcode casechange export formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
                        toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter pageembed permanentpen table',
                        toolbar_mode: 'floating',
                        tinycomments_mode: 'embedded',
                        tinycomments_author: 'Author name',
                        });

                    question_num = 1
                    $('#add_question').click(function(){
                        question_num ++
                        question_form = $('#question_form')

                        new_form = `
                        <div class="row mb-3">
                    <div class="col-lg-6 mb-3">
                        <label for="question${question_num}">Вопрос ${question_num}</label>

                        <textarea id="question${question_num}" name="question${question_num}" rows=20></textarea>
                    </div>
                    <div class="col-lg-6 mb-3">
                        <label for="answer${question_num}">Ответ на вопрос ${question_num}</label>
                        <textarea id="answer${question_num}" name="answer${question_num}" rows=20></textarea>
                    </div>
                    </div>
                    <hr>
                        `
                        question_form.append(new_form)

                    tinymce.init({
                        selector: `#question${question_num}`,
                        plugins: 'a11ychecker advcode casechange export formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
                        toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter pageembed permanentpen table',
                        toolbar_mode: 'floating',
                        tinycomments_mode: 'embedded',
                        tinycomments_author: 'Author name',
                        });

                    tinymce.init({
                        selector: `#answer${question_num}`,
                        plugins: 'a11ychecker advcode casechange export formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
                        toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter pageembed permanentpen table',
                        toolbar_mode: 'floating',
                        tinycomments_mode: 'embedded',
                        tinycomments_author: 'Author name',
                        });

                    })

                        



                    $('#save_questions').click(function(e){
                        e.preventDefault()
                        data = {}
                        for(var i=1; i<question_num+1;i++){
                            question = tinyMCE.get(`question${i}`).getContent()
                            answer = tinyMCE.get(`answer${i}`).getContent()

                            data[`question${i}`] = [question, answer]

                            csrf = $('body > div.container > div.wrapper > div.row > div.col-lg-8 > div > div > form > input[type=hidden]').val()
                            data['csrfmiddlewaretoken'] = csrf
                        }

                        $.ajax({
                            url: '',
                            method: 'post',
                            data: data,
                            success: function(data){
                                if(data['status'] == 201){
                                    host = localStorage.getItem('host')
                                    window.location.replace(`${host}/questions/subject/list/`);

                                }
                            }
                        });
                        
                    })
                        
                </script>

        </div>
    </div>

</div>





{% endblock content %}

core/templates/questions/questions_list.html
{% extends '../main/base.html' %}


{% block content %}

<div class="col-12 col-lg-8 col-xl-8 col-sm-12 col-md-12">
    {% if subject.questions.all%}
    {% for question in subject.questions.all %}
        <div class="row mb-3">
            <div class="col-xl-6">
                <div class="card">
                    <div class="card-header">
                        Вопрос {{ forloop.counter }}
                    </div>
                    <div class="card-body">
                        {{ question.question |safe }}
                        <a href="{% url 'questions:delete_questions' question_pk=question.pk %}" class="btn btn-primary">Удалить вопрос</a>
                    </div>
                </div>
            </div>

            <div class="col-xl-6">
                <div class="card">
                    <div class="card-header">

                        Ответ на вопрос {{ forloop.counter }}
                    </div>
                    <div class="card-body">
                        {{ question.answer_question.first.answer |safe }}
                    </div>
                </div>

            </div>
        </div> 
        <hr>
    {% endfor %}
    {% else %}

            <h4 class='mb-3'>Вы не добавили ни одного вопроса</h4>
{% endif %}
    

</div>



<script>

    var images = document.querySelectorAll('.card-body > p > img')
    for(i=0;i<images.length;i++){
        images[i].addEventListener('click', function(){
            $('#lightbox > span').css('background-image', `url('${this.src}')`)
            $('#lightbox').css('display', 'block')


        })
    }

   
</script>
{% endblock content %}

core/templates/questions/subject_list.html
{% extends '../main/base.html' %}

{% block content %}



<div class="col-12 col-lg-8 col-xl-8 col-sm-12 col-md-12">
    {% if subjects %}
    
   {% for subject in subjects %}
   <div class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <a href="{% url 'questions:all_questions' subject_pk=subject.pk %}" title='Посмотреть вопросы и ответы' class='subject_title'>
                        <h5 class="card-title">{{ subject.title }}</h5>
                    </a>
                </div>

                <div class="col-lg-6 float-end">
                    <a href="#" class="btn btn-primary">Учить</a>
                    <a href="{% url 'questions:add_question' subject_pk=subject.pk %}" class="btn btn-success">Добавить вопросы</a>
                    <a href="{% url 'questions:delete' pk=subject.pk %}" class="btn btn-danger">Удалить</a>
                    
                </div>
            </div>

        </div>
    </div>
   {% endfor %} 
   {% else %}

            <h4 class='mb-3'>Вы не добавили ни одного предмета</h4>

    {% endif %}
</div>

{% endblock content %}