core/accounts/urls.py
from django.urls import path
from .views import (user_login,
                    user_logout,
                    user_register,
                    current_subject_user,
                    next_random_question)


app_name = 'accounts'
urlpatterns = [
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register'),
    path('add/current_subject/',
         current_subject_user,
         name='add_current_subject'),
    path('get/random/question/<int:subject_pk>/',
         next_random_question,
         name='random_question')
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/main/urls.py
from django.urls import path
from .views import IndexView 


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

core/main/models.py
from django.db import models

# Create your models here.

core/main/views.py
from django import template
from django.shortcuts import render
from django.views.generic.base import TemplateView
from accounts.forms import LoginForm, UserRegisterForm
from questions.forms import AddSubjectForm


class IndexView(TemplateView):
    template_name = 'main/index.html'

    

core/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/6zwb1w1y4mgm9l95f973lfew85x35xuij3ou268qsa1io86t/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>



    <title>Fortest</title>

    <script>
        localStorage.setItem('host', 'http://127.0.0.1:8000')
    </script>
</head>

<body>

    <div class="container">
        <div class="wrapper">
            <!-- Navbar -->
                {% include '../includes/header.html' %} 
            <!-- end navbar -->


            <div class="row">

                <!-- Main Content -->
                <div class="info">
                    
                </div>
                {% if messages %}
                    <div class="message_block">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %} 
                </div>
                {% endif %}
               {% block content %}

               {% endblock content %} 
                <!-- end main content -->

                <!-- Sidebar -->
                {% include '../includes/sidebar.html' %}
                <!-- End sidebar -->
            </div>
            <!-- footer -->
            
                {% include '../includes/footer.html' %}
            <!-- End footer -->
        </div>

        <!-- Модальное окно ответа -->
        <!-- Scrollable modal -->
            {% include '../includes/modal_question.html' %}
        <!-- Конец модального окна ответа -->



        <!-- Модальное окно входа -->

       {% include '../includes/modal_auth.html' %} 

        <!-- Конец модального окна входа -->


        <!-- Модальное окно регистрации -->
        
        {% include '../includes/modal_reg.html' %}


        <!-- Конец модального окна регистрации -->


        {% include '../includes/modal_add_questions.html' %}


<div id="lightbox" style='display: none;'>
        <a href="#">&#10006;</a>
        <span></span>
    </div>

    </div>


</body>

<script src="{% static 'js/script.js' %}"></script>

<script>
    $('.drop-item').click(function(){
        pk = $(this).attr('data-pk')
        csrftoken = $('body > div > div.wrapper > div.top_nav > div.top-menu > div > div.col-xl-8.col-sm-12.col-md-12.col-lg-8.col-12 > div > ul > input[type=hidden]').val()
        data = {'subject_pk': pk,
                'csrfmiddlewaretoken': csrftoken}
        $.post("{% url 'accounts:add_current_subject'%}", data, function (data, textStatus, xhr) {
            console.log(data)
            if (data.status == 201) {
                host = localStorage.getItem('host')
                window.location.replace(host);
            }
            else if (data.status == 500){
                host = localStorage.getItem('host')
                window.location.replace(host)
            }
            else {

                $('.modal_reg_info').empty()
                $('.modal_reg_info').css('background-color', '#f85e5e')
                $('.modal_reg_info').css('display', 'block')
                for (var key in data.errors){
                    $('.modal_reg_info').append(data.errors[key] + '<br>')
                }
            }

        })

    })
</script>

<script>
 var image_question = document.querySelectorAll('#question-rotated > div.back > span > p > img')
    for(i=0;i<image_question.length;i++){
        image_question[i].addEventListener('click', function(){
            $('#lightbox > span').css('background-image', `url('${this.src}')`)
            $('#lightbox').css('display', 'block')
        })
    }
    console.log($('#lightbox > a'))
    $('#lightbox > a').click(function(e){
        e.preventDefault()
        $('#lightbox').css('display', 'none')
    })
</script>

</html>

core/templates/main/index.html
{% extends './base.html' %}

{% load static %}


{% block content %}

<div class="col-12 col-lg-8 col-xl-8 col-sm-12 col-md-12">

                    <div class="row">
                        <div class="col-xl-6">
                            <div class="question">
                                {% if user.is_authenticated %}
                                    <div class="question-header">
                                        Вопрос {{ count_user_questions }} из {{ count_questions }} 
                                    </div>
                                {% else %}
                                    <div class="question-header">
                                        Необходима авторизация
                                    </div>
                                {% endif %}
                                

                               <i></i> 
                               {% if user.is_authenticated %}
                                    <div class="question-text">
                                        {% if no_questions %}
                                            {{ no_questions }} 
                                        {% elif user.current_questions %}
                                            {{ user.current_questions.question |safe}}
                                        {% else %}
                                            Выберите предмет 
                                        {% endif %}
                                        
                                    </div>
                                {% else %}
                                    <div class="question-text">
                                        Необходима авторизация
                                    </div>
                               {% endif %}

                            </div>

                            {% if current_subject_user %}
                            
                            <a href="{% url 'accounts:random_question' subject_pk=current_subject_user.pk %}" class='ml-3 mb-3 btn btn-primary'>Следующий вопрос</a>
                            {% endif %}
                        </div>

                        <div class="col-xl-6">

                            <div id="question-rotated">

                                <div class="front">
                                    <img src="{% static 'img/预览图_千图网_编号25688649.jpg' %}">
                                </div>
                                <div class="back">
                                    {% if user.is_authenticated %}

                                    <span>{{ user.current_questions.answer_question.first.answer |truncatechars:700|safe}}
                                        <a href="#" type="button" class="btn btn-primary" data-bs-toggle="modal"
                                            data-bs-target="#staticBackdrop">Посмотреть полный ответ</a>
                                    </span>
                                    {% else %}
                                    Необходима авторизация
                                    {% endif %}
                                    

                                </div>
                                <div class="pop">
                                    <button id='pop-button'>Посмотреть ответ</button>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>




{% endblock content %}